[package]
name = "simulator"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = { version = "0.16.1", features = ["dynamic_linking", "bevy_dev_tools"] }
i_triangle = "0.36.3"
physics = {path = "../physics"}
rand = "0.9.2"
